import DisplayList from "./Product/ProductRenderItem";
import SearchList from "./Product/ProductSearch";
const imageSrc = [
  "https://images-na.ssl-images-amazon.com/images/I/81JLa2klprL._SL1500_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/81SjubboGoL._SL1500_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/9181rNz2sIL._SL1500_.jpg",
  "https://rukminim1.flixcart.com/image/832/832/j6v2ky80/computer/d/a/g/hp-na-laptop-original-imaex8fhspprkq3p.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/j6v2ky80/computer/z/n/z/dell-na-notebook-original-imaex8jwxedjtyxp.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/j7f2qvk0/computer/q/u/u/acer-2-in-1-laptop-original-imaexntyzat8vg8g.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/j63x7rk0/computer/m/w/a/lenovo-na-laptop-original-imaewfhdwnxdzdhc.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/jh0vb0w0/computer/a/u/3/lenovo-na-laptop-original-imaf5557z2psj3p2.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/j7asfbk0/computer/h/z/h/dell-na-laptop-original-imaexkmjm8dufspd.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/jhkvgy80/computer/g/g/h/hp-na-laptop-original-imaf5kd4ac9hggrn.jpeg?q=70",
  "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c05962448.png",
  "http://www.liberianmarket.com/wp-content/uploads/2015/07/best-laptop-under-400-550x336.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_egmore.jpeg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_t.nagar.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_meenambakkam.png",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_mount%20road.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_triplicane.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_vadapalani.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_annanagar.png",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_ambattur.png",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_thiruvanmiyur.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_nungambakkam.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_teynampet.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/81SjubboGoL._SL1500_.jpg",
  "https://images-na.ssl-images-amazon.com/images/I/9181rNz2sIL._SL1500_.jpg",
  "https://rukminim1.flixcart.com/image/832/832/j7asfbk0/computer/h/z/h/dell-na-laptop-original-imaexkmjm8dufspd.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/jhkvgy80/computer/g/g/h/hp-na-laptop-original-imaf5kd4ac9hggrn.jpeg?q=70",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_egmore.jpeg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_t.nagar.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_egmore.jpeg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_t.nagar.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_meenambakkam.png",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_mount%20road.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_vadapalani.jpg",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_annanagar.png",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_ambattur.png",
  "http://hpservicecenterschennai.in/images/hp_laptop_service_centers_in_thiruvanmiyur.jpg",
  "https://rukminim1.flixcart.com/image/832/832/j6v2ky80/computer/z/n/z/dell-na-notebook-original-imaex8jwxedjtyxp.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/j7f2qvk0/computer/q/u/u/acer-2-in-1-laptop-original-imaexntyzat8vg8g.jpeg?q=70",
  "https://rukminim1.flixcart.com/image/832/832/j63x7rk0/computer/m/w/a/lenovo-na-laptop-original-imaewfhdwnxdzdhc.jpeg?q=70"
];

export { DisplayList, SearchList, imageSrc };
