export const REQUEST_API = "REQUEST_API";
export const RECEIVE_API = "RECEIVE_API";
export const PRODUCT_SEARCH_LIST = "PRODUCT_SEARCH_LIST";

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const PRODUCT_AVAILABLE = "PRODUCT_AVAILABLE";
export const PRODUCT_UNAVAILABLE = "PRODUCT_UNAVAILABLE";
export const SEARCH_PRODUCT_LIST = "SEARCH_PRODUCT_LIST";
